### ISSUE TITLE
Conflict with Redmine tweaks plugin \ Help link

### ISSUE THREAD

**Issue by kushlces** [chiliproject-eu/chiliproject_look_and_feel#2]
Hi,
First, thanks for making this plugin available :).
We use [Redmine Tweaks](https://www.redmine.org/plugins/redmine_tweaks) for our installation. We don't want "Help" link so we remove(disable) it with "Redmine Tweaks" plugin.
Then, if we use your plugin, redmine fails giving internal server error.
The issue is related to base.html.erb. If we comment following line -
      <%= render_menu_node(help_menu_item) %>
Then, redmine works fine. Maybe you can conditionally display help menu?
Again, thanks for your help and keep up the great work.
Kush

**Comment by svoboda-jan** [comment]
Hi,

This error is because we don't expect that somebody will remove that item, but since this works with original redmine, I fixed it adding a condition to check the presence of `help_menu_item` and created a new release.

You can download the new version here:
https://github.com/chiliproject-eu/chiliproject_look_and_feel/releases/tag/v0.0.4

**Comment by kushlces** [comment]
Thanks so much for your help. Really appreciate your prompt response.
Kush
